stages:
  prepare_data:
    cmd: python src/stage_01_prepare.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_01_prepare.py
      - data/data.xml
      - src/utils/all_utils.py
      - src/utils/data_mngt.py
      - config/config.yaml
    params:
      - prepare.seed
      - prepare.split
    outs:
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv

  featurize:
      cmd: python src/stage_02_featurization.py --config=config/config.yaml --params=params.yaml
      deps:
        - src/stage_02_featurization.py
        - artifacts/prepared/train.tsv
        - artifacts/prepared/test.tsv
        - src/utils/all_utils.py
        - src/utils/featurize.py
        - config/config.yaml
        - params.yaml
      params:
        - featurize.max_features
        - featurize.ngrams
      outs:
        - artifacts/features/train.pkl
        - artifacts/features/test.pkl